spring:
  kafka:
    producer:
      bootstrap-servers:
        - 10.168.55.88:9093
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers:
        - 10.168.55.88:9093
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      enable-auto-commit: false
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: com.chinamobile.rcs.aih.model

kafka:
  topic:
    group-id: my-consumer-group
    name: my-topic