
server:
  port: 8081

app:
  name: WEBTOOL

common:
  #name: ${test.name:James}
  name: ${TEST_NAME:James}

http:
  maxTotal: 200
  defaultMaxPerRoute: 50
  connectTimeout: 2000
  connectionRequestTimeout: 4000
  socketTimeout: 3000
  retryCount: 0
  requestSentRetryEnabled: false

info:
  app:
    encoding: utf-8
    java:
      source: 1.8
      target: 1.8

management:
  endpoints:
    web:
      exposure:
        include: health,info,beans
