server:
  port: 8081
  tomcat:
    accept-count: 20
    max-connections: 40
    max-threads: 20
    uri-encoding: utf-8

http:
  maxTotal: 200
  defaultMaxPerRoute: 50
  connectTimeout: 2000
  connectionRequestTimeout: 4000
  socketTimeout: 3000
  retryCount: 0
  requestSentRetryEnabled: false

app:
  name: WEBTOOL

common:
  #name: ${test.name:James}
  name: ${TEST_NAME:James}

spring:
  redis:
    primary:
      name: primary
      host: 10.153.61.38
      port: 8579
      password: attCka123#mm
      database: 3  #数据库索引
      timeout: 60000  #连接超时时间
      max-idle: 10 #最大空闲连接
      min-idle: 0 #最小空闲连接
      max-active: 10  #最大连接数
      max-wait: -1 #最大阻塞等待时
      cacheable-second: 3600 #cacheable默认存储时间  单位:秒
    secondaries:
      - name: secondary1
        host: 10.153.61.38
        port: 8579
        password: attCka123#mm
        database: 3  #数据库索引
        timeout: 60000  #连接超时时间
        max-idle: 10 #最大空闲连接
        min-idle: 0 #最小空闲连接
        max-active: 10  #最大连接数
        max-wait: -1 #最大阻塞等待时
        cacheable-second: 3600 #cacheable默认存储时间  单位:秒
