#  使用springbooter自带的数据源-HikariCP
spring:
  datasource:
    url: jdbc:mysql://10.168.55.88:3306/test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 12345678