spring:
  redis:
    primary:
      host: 10.153.61.38
      port: 8579
      password: attCka123#mm
      database: 3  #数据库索引
      timeout: 60000  #连接超时时间
      max-idle: 10 #最大空闲连接
      min-idle: 0 #最小空闲连接
      max-active: 10  #最大连接数
      max-wait: -1 #最大阻塞等待时
      cacheable-second: 3600 #cacheable默认存储时间  单位:秒
    secondaryMap:
      secondary1:
        host: 10.153.61.38
        port: 8579
        password: attCka123#mm
        database: 0  #数据库索引
        timeout: 60000  #连接超时时间
        max-idle: 10 #最大空闲连接
        min-idle: 0 #最小空闲连接
        max-active: 10  #最大连接数
        max-wait: -1 #最大阻塞等待时
        cacheable-second: 3600 #cacheable默认存储时间  单位:秒